name: Scrape
on:
  workflow_dispatch:
    inputs:
      containerTag:
        default: "latest"
        required: false
        description: "Container tag to use"
      sendNewConfigToTg:
        description: "Send current config via Telegram (true/false)"
        type: boolean
        required: false
        default: false
      DEBUG:
        description: "Debug logging namespace"
        required: false
        default: "moneyman:*"
  schedule:
    - cron: "5 10,22 * * *"
env:
  REGISTRY: ghcr.io
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - id: normalize-repository-name
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - id: set-container-image
        run: echo "image=${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:${{ github.event.inputs.containerTag || 'latest' }}" >> $GITHUB_OUTPUT
      - name: Pull container image
        run: docker pull ${{ steps.set-container-image.outputs.image }}
      - name: Create config file
        run: |
          cat > /tmp/moneyman.conf.jsonc << 'EOF'
          {
            "outputVendors": {
              "supabase": {
                "active": true,
                "url": "${{ secrets.MONEYMAN_SUPABASE_URL }}",
                "apiKey": "${{ secrets.MONEYMAN_SUPABASE_KEY }}",
                "tableName": "expenses"
              }
            },
            "accounts": [
              {
                "id": "max",
                "key": "max",
                "active": true,
                "credentials": {
                  "username": "${{ secrets.MONEYMAN_MAX_USER_ID }}",
                  "password": "${{ secrets.MONEYMAN_MAX_PASSWORD }}"
                }
              }
            ]
          }
          EOF
      - name: Run scraper
        run: >
          docker run --rm
          -v /tmp/moneyman.conf.jsonc:/tmp/moneyman.conf.jsonc
          -e MONEYMAN_CONFIG_PATH=/tmp/moneyman.conf.jsonc
          -e TZ
          ${{ steps.set-container-image.outputs.image }}
        env:
          TZ: "Asia/Jerusalem"
